### PR TITLE
[FEATURE] Added search function to Reflection Explorer

### PR DESCRIPTION
**Pull request by CapslockRSPS**
This searches for the VALUE that the field currently has.

Doesn't work with PKHonor for some reason.

### CODE REVIEW

**Comment by CapslockRSPS** [comment]
NOTE: This searches for the VALUE that the field currently has.

**Comment by JKetelaar** [comment]
Could you provide a gif/video of your functionality.

**Comment by CapslockRSPS** [comment]
e9e6c68f5593fbc195645712875c5db3

**Comment by JKetelaar** [comment]
Thanks for the image.

What if there's multiple fields with the same value.
Would it be possible to fill in the left side of the panel?

**Comment by JKetelaar** [comment]
Could you push your latest code too?

**Comment by JKetelaar** [comment]
Looking great, waiting for the CI

**Pull request merged**
